language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  global:
    - BEANSTALKD=./beanstalkd

install:
    # Install most recent beanstalkd from source
    - wget https://github.com/kr/beanstalkd/archive/v1.10.tar.gz
    - tar xf v1.10.tar.gz
    - make -C beanstalkd-1.10/
    - mv beanstalkd-1.10/beanstalkd .
    - pip install pyyaml
script: python test.py
